#!/usr/bin/env ts-node

/**
 * Daily Brief Cron Job for FacadeFlow
 *
 * This script is designed to be run by OpenClaw's cron scheduler.
 * It fetches project data from FacadeFlow and sends a formatted
 * daily brief to Telegram.
 *
 * Usage with OpenClaw cron:
 * {
 *   "name": "FacadeFlow Daily Brief",
 *   "schedule": { "kind": "cron", "expr": "0 7 * * *", "tz": "Europe/Sofia" },
 *   "payload": {
 *     "kind": "agentTurn",
 *     "message": "Run daily brief from FacadeFlow",
 *     "model": "openrouter/anthropic/claude-3.5-sonnet",
 *     "thinking": "high"
 *   },
 *   "delivery": { "mode": "announce", "channel": "telegram" }
 * }
 */

import { message } from 'openclaw-messaging';
import { memory, memory_search } from 'openclaw-memory-tools';
import { web_fetch } from 'openclaw-tools-available';

// Configuration
const API_URL = process.env.FACADEFLOW_API_URL || 'http://localhost:3000/api';
const API_KEY = process.env.FACADEFLOW_API_KEY;
const TELEGRAM_CHAT_ID = process.env.TELEGRAM_CHAT_ID || '6965983037'; // Default to your chat

interface DailySummary {
  active_projects: number;
  overdue_tasks: number;
  today_appointments: number;
  estimates_sent_this_week: number;
  revenue_pipeline: number;
  items: Array<{
    type: 'project' | 'task' | 'estimate' | 'client' | 'appointment';
    id: string;
    title: string;
    description?: string;
    due_date?: string;
    priority?: string;
  }>;
}

async function main() {
  console.log('[DailyBrief] Starting...');

  try {
    // 1. Fetch data from FacadeFlow
    const summary = await fetchDailySummary();

    // 2. Format message
    const formattedMessage = formatMessage(summary);

    // 3. Send to Telegram
    await sendTelegram(formattedMessage);

    // 4. Log to memory
    await logToMemory(summary);

    console.log('[DailyBrief] Completed successfully');
    process.exit(0);
  } catch (error: any) {
    console.error('[DailyBrief] Failed:', error);
    // Send error notification
    await message({
      action: 'send',
      to: TELEGRAM_CHAT_ID,
      message: `❌ Daily Brief failed: ${error.message}`,
    });
    process.exit(1);
  }
}

async function fetchDailySummary(): Promise<DailySummary> {
  const response = await web_fetch(`${API_URL}/dashboard/daily-brief`, {
    method: 'GET',
    headers: {
      Authorization: `Bearer ${API_KEY}`,
    },
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  const data = await response.json();
  return data as DailySummary;
}

function formatMessage(summary: DailySummary): string {
  const today = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  let message = `🌅 *Daily Brief - ${today}*\n\n`;

  // Summary section
  message += `📊 *Executive Summary*\n`;
  message += `• Active Projects: ${summary.active_projects}\n`;
  message += `• Overdue Tasks: ${summary.overdue_tasks}\n`;
  message += `• Today's Appointments: ${summary.today_appointments}\n`;
  message += `• Estimates Sent (This Week): ${summary.estimates_sent_this_week}\n`;
  message += `• Revenue Pipeline: $${summary.revenue_pipeline.toLocaleString()}\n\n`;

  // Action Items
  if (summary.items.length > 0) {
    message += `📋 *Action Items (${summary.items.length})*\n`;
    summary.items.forEach((item, idx) => {
      const emoji = getItemEmoji(item.type);
      const priority = item.priority ? ` [${item.priority.toUpperCase()}]` : '';
      const due = item.due_date ? ` (Due: ${new Date(item.due_date).toLocaleDateString()})` : '';
      message += `${idx + 1}. ${emoji} ${item.title}${priority}${due}\n`;
      if (item.description) {
        message += `   └ ${item.description.slice(0, 100)}${item.description.length > 100 ? '...' : ''}\n`;
      }
    });
  } else {
    message += `📋 *Action Items*\n`;
    message += `Clear for today! 🎉\n`;
  }

  message += `\n_Generated by Canyon AI at ${new Date().toLocaleTimeString()}_`;

  return message;
}

function getItemEmoji(type: string): string {
  switch (type) {
    case 'project': return '🏗️';
    case 'task': return '✅';
    case 'estimate': return '💰';
    case 'client': return '👤';
    case 'appointment': return '📅';
    default: return '📌';
  }
}

async function sendTelegram(text: string): Promise<void> {
  const response = await web_fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/sendMessage`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      chat_id: TELEGRAM_CHAT_ID,
      text,
      parse_mode: 'Markdown',
      disable_web_page_preview: true,
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`Telegram API error: ${response.status} - ${err}`);
  }

  const result = await response.json();
  if (!result.ok) {
    throw new Error(`Telegram error: ${result.description}`);
  }

  console.log('[DailyBrief] Telegram message sent');
}

async function logToMemory(summary: DailySummary): Promise<void> {
  const logEntry = {
    date: new Date().toISOString().split('T')[0],
    type: 'daily_brief',
    summary,
    sent: true,
  };

  // Store in daily memory file
  const memoryPath = `memory/daily_briefs.json`;
  let existing = [];
  try {
    const current = await memory_get({ path: memoryPath });
    existing = JSON.parse(current);
  } catch {
    // File doesn't exist yet
  }

  existing.push(logEntry);

  // Could also update MEMORY.md with insights
  await memory({
    action: 'write',
    path: memoryPath,
    content: JSON.stringify(existing, null, 2),
  });
}

// Run if executed directly
if (require.main === module) {
  main().catch(console.error);
}

export { main as dailyBriefCron };
